# Fluent Bit - 服务器 A（采集 huiyuce_app 项目文件日志）
[SERVICE]
    Flush         5
    Daemon        off
    Log_Level     info
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

# api 类服务日志
[INPUT]
    Name              tail
    Tag               app.huiyuce
    Path              /work/projectData/api/*/data/logs/*/*.log
    Parser            huiyuce_app
    Path_Key          filepath
    Refresh_Interval  5
    Rotate_Wait       30
    Mem_Buf_Limit     20MB
    Skip_Long_Lines   On

# admin 类服务日志
[INPUT]
    Name              tail
    Tag               app.huiyuce
    Path              /work/projectData/admin/*/data/logs/*/*.log
    Parser            huiyuce_app
    Path_Key          filepath
    Refresh_Interval  5
    Rotate_Wait       30
    Mem_Buf_Limit     20MB
    Skip_Long_Lines   On

[FILTER]
    Name   lua
    Match  app.huiyuce
    script /fluent-bit/etc/map_huiyuce_labels.lua
    call   cb_map

[FILTER]
    Name          record_modifier
    Match         app.huiyuce
    Record        host ${GAOBAO_HOST}
    Record        env ${GAOBAO_ENV}

[OUTPUT]
    Name                   loki
    Match                  app.huiyuce
    Host                   127.0.0.1
    Port                   3100
    Labels                 job=huiyuce_app, env=${GAOBAO_ENV}, host=${GAOBAO_HOST}, container=$container_name, source=app_file
    Auto_Kubernetes_Labels off
